johnpapa/angular-ngrx-data

src/client/app/store/hero-data.service.ts, src/client/app/store/hero.action.ts, src/client/app/store/hero.effects.ts, src/client/app/store/hero.reducer.ts
doing or for Ward's stuff so we can see it
=> Ward refactors and fixes bug with the error handling

src/client/ngrx-data/entity.effects.ts, src/client/ngrx-data/entity.reducer.ts, src/client/ngrx-data/interfaces.ts
- Refactored effects and reducers accordingly
- Removed the unused and pointless EntityCollection.error
- Simplified, corrected, commented EntityReducer
=> EntityAction.type string includes entity type name

src/client/app/heroes/hero-detail.component.ts, src/client/app/heroes/hero-list.component.ts, src/client/app/villains/villain-detail.component.ts, src/client/app/villains/villain-list.component.ts, src/client/ngrx-data/entity.selectors.ts
using reactive forms for the filter.
id is no longer required.
id is not shown during "add" mode
closes #23
closes #24
closes #62
=> using reactive forms for the filter and id fixes

src/client/app/heroes/hero-detail.component.ts, src/client/app/villains/villain-detail.component.ts, src/server/models/counter.js, src/server/models/hero.model.js, src/server/models/villain.model.js, src/server/services/hero.service.js
increments the mongodb IDs in a counter collection, keyed by entity
=> increment id's in the database. uses a counter collection

src/client/app/core/core.module.ts, src/client/app/core/index.ts, src/client/app/core/toast.service.ts, src/client/app/core/toolbar/toolbar.component.scss, src/client/app/heroes/hero-detail/hero-detail.component.html, src/client/app/heroes/hero-detail/hero-detail.component.scss, src/client/app/heroes/hero-list/hero-list.component.html, src/client/app/heroes/hero-list/hero-list.component.scss, src/client/app/heroes/hero-list/hero-list.component.ts, src/client/app/shared/shared.module.ts, src/client/app/store/entity-store.module.ts, src/client/app/villains/villain-detail/villain-detail.component.html, src/client/app/villains/villain-detail/villain-detail.component.scss, src/client/app/villains/villain-list/villain-list.component.html, src/client/app/villains/villain-list/villain-list.component.scss, src/client/app/villains/villain-list/villain-list.component.ts, src/client/styles/styles.scss
closes #79 
closes #77 
- Lots of styling for the Form controls
- Added a `ToastService` using the snackbar
- Addressed the `saying` text being too long with ellipsis
- Made `saying` a `textarea`
- Added icons for the delete of a villain or hero
TOD:
- still need to address how and when and where to send toasts
=> Material forms

src/client/app/heroes/hero-list/hero-list.component.html, src/client/app/heroes/hero-list/hero-list.component.ts, src/client/app/shared/filter/filter.component.html, src/client/app/shared/filter/filter.component.ts, src/client/app/shared/shared.module.ts, src/client/app/villains/villain-list/villain-list.component.html, src/client/app/villains/villain-list/villain-list.component.ts
=> abstract filter to a component

src/client/app/heroes/hero-list/hero-list.component.html, src/client/app/heroes/hero-list/hero-list.component.scss, src/client/app/heroes/hero-list/hero-list.component.ts, src/client/app/heroes/hero-search/hero-search.component.html, src/client/app/heroes/hero-search/hero-search.component.scss, src/client/app/heroes/hero-search/hero-search.component.ts, src/client/app/heroes/heroes-routing.module.ts, src/client/app/heroes/heroes.module.ts, src/client/app/shared/filter/filter.component.html, src/client/app/shared/filter/filter.component.scss, src/client/app/villains/villain-list/villain-list.component.html, src/client/app/villains/villain-list/villain-list.component.scss, src/client/app/villains/villain-list/villain-list.component.ts, src/client/app/villains/villain-search/villain-search.component.html, src/client/app/villains/villain-search/villain-search.component.scss, src/client/app/villains/villain-search/villain-search.component.ts, src/client/app/villains/villains-routing.module.ts, src/client/app/villains/villains.module.ts
=> Comp shuffle

package.json, src/client/app/store/entity-store.module.ts, src/client/ngrx-data/basic-data.service.spec.ts, src/client/ngrx-data/basic-data.service.ts, src/client/ngrx-data/entity-data.service.spec.ts, src/client/ngrx-data/entity-data.service.ts, src/client/ngrx-data/entity-definition.service.spec.ts, src/client/ngrx-data/entity-definition.service.ts, src/client/ngrx-data/entity-definition.spec.ts, src/client/ngrx-data/entity-definition.ts, src/client/ngrx-data/entity-dispatcher.spec.ts, src/client/ngrx-data/entity-dispatcher.ts, src/client/ngrx-data/entity-filters.spec.ts, src/client/ngrx-data/entity-filters.ts, src/client/ngrx-data/entity-metadata.ts, src/client/ngrx-data/entity.actions.spec.ts, src/client/ngrx-data/entity.actions.ts, src/client/ngrx-data/entity.effects.marbles.spec.ts, src/client/ngrx-data/entity.effects.spec.ts, src/client/ngrx-data/entity.effects.ts, src/client/ngrx-data/entity.reducer.spec.ts, src/client/ngrx-data/entity.reducer.ts, src/client/ngrx-data/entity.selectors.spec.ts, src/client/ngrx-data/entity.selectors.ts, src/client/ngrx-data/entity.service.ts, src/client/ngrx-data/interfaces.ts, src/client/ngrx-data/ngrx-data.module.ts, src/client/ngrx-data/ngrx-entity-models.ts, src/client/ngrx-data/pluralizer.spec.ts, src/client/ngrx-data/pluralizer.ts
**WIP - a few more to go**
Add tests to the  `ngrx-data` library.
Fix the bugs/design flaws those tests reveal.
=> [WIP] Add tests to ngrx-data library

docs/faq.md
There is a broken link to entity-metadata.md from faq.md. This fixes it!
=> Fixing link in doc.

CHANGELOG.md, docs/README.md, docs/entity-effects.md, docs/entity-reducer.md, docs/extension-points.md, docs/reply-to-mike.md, lib/package.json, lib/src/entity-collection.reducer.ts, lib/src/entity.reducer.spec.ts, lib/src/entity.reducer.ts, lib/src/interfaces.ts, lib/src/ngrx-data.module.ts
Adds a customization/extension point for entity collection reducers.
Adds the first documentation of reducers (and a little about effects).
=> feat: add entityCollectionMetaReducers and reducer doc

docs/publishing-checklist.md, lib/CHANGELOG.md, lib/package.json, lib/src/default-data.service.spec.ts, lib/src/default-data.service.ts, lib/src/entity-collection.reducer.spec.ts, package-lock.json, package.json, tslint.json
- also updated TSLint to the one CLI is using
- adjusted TSLint rules, removing those that it no longer recognizes
- release alpha.6
=> feat: add error handling (and tests) to DefaultDataService

CHANGELOG.md, docs/entity-metadata.md, docs/entity-service.md, docs/introduction.md, lib/CHANGELOG.md, lib/package.json, lib/src/entity-collection.reducer.spec.ts, lib/src/entity-commands.ts, lib/src/entity-definition.service.spec.ts, lib/src/entity-definition.service.ts, lib/src/entity-dispatcher.spec.ts, lib/src/entity-dispatcher.ts, lib/src/entity-metadata.ts, lib/src/entity.reducer.spec.ts, lib/src/entity.selectors$.ts, lib/src/entity.service.ts, package.json, src/client/app/heroes/heroes-routing.module.ts, src/client/app/heroes/heroes.module.ts, src/client/app/heroes/heroes.service.ts, src/client/app/heroes/heroes/heroes.component.html, src/client/app/heroes/heroes/heroes.v1.component.ts, src/client/app/store/entity-metadata.ts, src/client/app/villains/villains.service.ts, src/client/app/villains/villains/villains.component.html, src/client/app/villains/villains/villains.component.ts
* alpha.9
* see ChangeLog for explanation.
=> refactor: can make concrete EntityService<T> with EntityServiceBase<T>

CHANGELOG.md, lib/CHANGELOG.md, lib/package.json, lib/src/actions/entity-action.spec.ts, lib/src/actions/entity-op.ts, lib/src/dispatchers/entity-dispatcher.spec.ts, lib/src/dispatchers/entity-dispatcher.ts, lib/src/effects/entity-effects.marbles.spec.ts, lib/src/effects/entity-effects.spec.ts, lib/src/effects/entity-effects.ts, lib/src/reducers/entity-collection.reducer.spec.ts, lib/src/reducers/entity-collection.reducer.ts, lib/src/reducers/entity-reducer.ts, package.json, src/client/app/heroes/heroes/heroes.component.spec.ts
Demonstrate how you might add tests to a user-land component that depends upon ngrx-data.
Because these tests lead to small changes to the library there is a new release, `alpha.11`.
```
[x] Yes 
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe:  Adds tests
```
=> Demonstrate component integration tests with ngrx-data

docs/entity-actions.md, docs/entity-reducer.md, lib/CHANGELOG.md, lib/package.json, lib/src/actions/entity-cache-actions.ts, lib/src/actions/index.ts, lib/src/entity-service/entity.service.spec.ts, lib/src/entity-service/entity.service.ts, lib/src/reducers/entity-reducer.spec.ts, lib/src/reducers/entity-reducer.ts, lib/src/selectors/entity-selectors$.spec.ts, lib/src/selectors/entity-selectors$.ts
=> feat: add EntityCache-level actions and reducer cases

docs/introduction.md
Typo fixed: ispatches to Dispatches
* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...
=> Typo fixed

CHANGELOG.md, package.json, src/client/app/core/index.ts, src/client/app/core/master-detail-commands.ts, src/client/app/heroes/hero-detail/hero-detail.component.html, src/client/app/heroes/hero-detail/hero-detail.component.ts, src/client/app/heroes/hero-list/hero-list.component.ts, src/client/app/heroes/heroes/heroes.component.effects.spec.ts, src/client/app/heroes/heroes/heroes.component.html, src/client/app/heroes/heroes/heroes.component.spec.ts, src/client/app/heroes/heroes/heroes.component.ts, src/client/app/heroes/heroes/heroes.v1.component.ts, src/client/app/villains/villain-detail/villain-detail.component.html, src/client/app/villains/villain-detail/villain-detail.component.ts, src/client/app/villains/villain-editor/villain-editor.component.html, src/client/app/villains/villain-editor/villain-editor.component.ts, src/client/app/villains/villain-list/villain-list.component.ts, src/client/app/villains/villains/villains.component.html, src/client/app/villains/villains/villains.component.ts
Updated the sample app so that its component code more closely matches that in [ngrx-data-lab](https://github.com/johnpapa/ngrx-data-lab)
=> refactor: update sample app to ngrx-data-lab

CHANGELOG.md, lib/CHANGELOG.md, lib/package.json, lib/src/dataservices/default-data.service.spec.ts, lib/src/dataservices/default-data.service.ts, lib/src/dataservices/entity-data.service.spec.ts, lib/src/dataservices/http-url-generator.ts, lib/src/utils/pluralizer.ts, package.json, src/client/app/store/entity-metadata.ts, src/client/app/store/entity-store.module.ts
See CHANGELOGS
Modified app and tests to demonstrate.
=> feat: add ability to set known HttpResourceUrls (beta.2)

CHANGELOG.md, lib/CHANGELOG.md, lib/package.json, lib/src/dataservices/http-url-generator.ts, lib/src/ngrx-data.module.spec.ts, lib/src/ngrx-data.module.ts, package.json, src/client/app/store/entity-store.module.ts
* also fix "trailing slash" bug that broke hero update & delete.
=> feat: can replace EntityEffects via providers (beta-3)

lib/CHANGELOG.md, lib/package.json, lib/src/entity-metadata/entity-definition.spec.ts, lib/src/entity-metadata/entity-definition.ts, lib/src/entity-service/default-entity-service-factory.ts, lib/src/entity-service/entity-service-base.ts, lib/src/entity-service/entity-service-interfaces.ts, lib/src/entity-service/entity-service.spec.ts, lib/src/entity-service/entity.service.ts, lib/src/entity-service/index.ts, lib/src/ngrx-data.module.ts, lib/src/selectors/entity-selectors$.spec.ts, lib/src/selectors/entity-selectors$.ts, lib/src/selectors/entity-selectors.spec.ts, lib/src/selectors/entity-selectors.ts, lib/src/selectors/related-entity-selectors.spec.ts, src/client/app/store/entity-metadata.ts
See CHANGELOG and `lib/src/selectors/related-entity-selectors.spec`.
=> Feature: support related entity selectors - Beta 10

lib/CHANGELOG.md, lib/package.json, lib/src/dataservices/default-data.service.spec.ts, lib/src/dataservices/default-data.service.ts, lib/src/effects/entity-effects.marbles.spec.ts, lib/src/effects/entity-effects.spec.ts, lib/src/reducers/default-entity-collection-reducer-methods.ts, lib/src/reducers/entity-collection-reducer.spec.ts, package-lock.json, package.json, src/app/store/entity/entity-metadata.ts
=> fix: pessimistic delete should remove item from collection (v6.beta-4)

lib/CHANGELOG.md, lib/package.json, lib/src/actions/entity-cache-action.ts, lib/src/entity-services/entity-collection-service-base.ts, lib/src/entity-services/entity-collection-service-elements-factory.ts, lib/src/entity-services/entity-services-base.ts, lib/src/entity-services/entity-services-elements.ts, lib/src/reducers/entity-cache-reducer-factory.ts, lib/src/reducers/entity-cache-reducer.spec.ts
Beta 10: Added ClearCollections and LoadCollections entity cache actions. 
Other minor improvements for testability. See ChangeLog.
=> feat: ClearCollections, LoadCollections, testability improvements (beta-10)

README.md
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> Fix path for 'Explore this repository'

docs/limitations.md
* ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...
=> docs: typo in limitations

docs/entity-services.md
* ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...
=> docs: typo in entity-services

README.md
* Added a simple section for troubleshooting installation, like during `npm install`.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
* Read and review doc changes manually.
Verify that the following are valid
* Grammar
* Placement of the new section and its link added
NA
=> Added section for troubleshooting installation

docs/save-entities.md, lib/CHANGELOG.md, lib/package.json, lib/src/dataservices/entity-cache-data.service.ts, lib/src/effects/entity-cache-effects.spec.ts, lib/src/effects/entity-cache-effects.ts, src/in-memory-data.service.ts
Alpha 3 of the `saveEntities` series. See ChangeLog.
=> feat: allow server to respond 204-No Content after saveEntities

lib/CHANGELOG.md, lib/package.json, lib/src/dataservices/data-service-error.spec.ts, lib/src/dataservices/data-service-error.ts, lib/src/dispatchers/entity-dispatcher-base.ts, lib/src/entity-services/entity-collection-service-base.ts
This PR becomes `6.1.0-beta.3`
Small non-breaking changes. See changelog.
closes #201
=> refactor: DataServiceError.message and more (beta.3)
